spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-auth
          uri: lb://auth-service/
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-service-swagger-docs
          uri: lb://auth-service/
          predicates:
            - Path=/v3/api-docs/**

        - id: auth-service-swagger-ui
          uri: lb://auth-service/
          predicates:
            - Path=/swagger-ui/**

        - id: auth-service-groups
          uri: lb://auth-service/
          predicates:
            - Path=/api/v1/group/**

        - id: auth-service-user
          uri: lb://auth-service/
          predicates:
            - Path=/api/v1/user/**

        - id: auth-service-role
          uri: lb://auth-service/
          predicates:
            - Path=/api/v1/role/**

        - id: auth-service-permission
          uri: lb://auth-service/
          predicates:
            - Path=/api/v1/permission/**

        - id: audit-trail-service
          uri: lb://audit-trail-service/
          predicates:
            - Path=/api/v1/auditLog/**

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web/**
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:https://keycloak:8080/realms/QssenceRealm}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:https://keycloak:8080/realms/QssenceRealm/protocol/openid-connect/certs}
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
server:
  port: ${SERVER_PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - configprops
  health:
    mongo:
      enabled: false
